import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import { sanityClient, urlFor } from '../lib/sanity';
import styles from '../styles/Home.module.css';

const recipesQuery = '*[_type == "recipe"]{_id, name, slug, mainImage}';

export default function Home({ recipes }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to <em>The Kitchen</em></h1>
      <ul className="recipes-list">
        {recipes?.length && recipes.map(recipe => (
          <li key={recipe._id} className="recipe-card">
            <Link href={`/recipes/${recipe.slug.current}`}>
              <a>
                <Image className="recipe-card-img"
                  alt={recipe.name}
                  src={urlFor(recipe.mainImage).url()}
                  width={500}
                  height={500}
                />
                <span>{recipe.name}</span>
              </a>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipesQuery);
  return { props:{ recipes }};
}
